import React from "react";
import IngredientsList from "./IngredientsList";
import ClaudeRecipe from "./ClaudeRecipe";
import { useEffect, useRef } from "react";

function Main() {
  // to store the ingredients added by the user
  const [Ingredients, setIngredients] = React.useState([]);
  //to store the recipe generated by ai
  const [Recipe, setRecipe] = React.useState("");

  const recipeRef = useRef(null)

  // scroll to the recipe whenever it is generated
  useEffect(() => {
    if(Recipe!==null && recipeRef !== null) {
      recipeRef.current.scrollIntoView({behaviour:"smooth"})
    }
  },[Recipe])

  // add the new ingredient to the ingredients state
  function handleSubmit(formData) {
    const newIngredient = formData.get("ingredient");
    setIngredients((prev) => [...prev, newIngredient]);
  }


  // to send the ingredients to backend and receive the recipe 
  async function generateRecipe() {
    try {
      const response = await fetch("http://localhost:3333/sendRecipe", {
        method:"POST",
        headers: {
          "Content-Type":"application/json",
        },
        body: JSON.stringify({ingredients: Ingredients}),
      });

      if(!response.ok) {
        throw new Error("Failed to fetch recipe");
      }

      const data = await response.json();
      setRecipe(data.recipe);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <main>
      <form action={handleSubmit} className="add-ingredient-form">
        <input
          type="text"
          placeholder="Add Atleast 3 Ingredients"
          name="ingredient"
          aria-label="Add ingredient"
        />
        <button>Add Ingredient</button>
      </form>

      <IngredientsList list={Ingredients} genRecipe={generateRecipe} />
      <ClaudeRecipe ref={recipeRef} recipe={Recipe} /> 
    </main>
  );
}

export default Main;
